### ISSUE TITLE
no captcha image shown

### ISSUE THREAD

**Issue by derBoogie** [einpraegsam/captcha#1]
I tested Version 2.0.2 with TYPO3 6.2.29 in a powermail form (version 2.25.2) and no captcha image was rendered. Firebug shows: 500 Internal Server Error - https://www.gwh.de/typo3conf/ext/captcha/captcha/captcha.php

Greetings TJ

**Comment by einpraegsam** [comment]
Version 2 is not supported any more. 3.14 is the current version.

**Comment by derBoogie** [comment]
And where can I download version 3.14?

**Comment by einpraegsam** [comment]
Oh, sorry, my mistake - I thoght you talk about powermail.
This repo is the wrong place for captcha issues. Please contact the author (e.g. via Slack).
